### ISSUE TITLE
Lazy Load Breaks

### ISSUE THREAD

**Issue by wirmachenbunt** [distantnative/oembed#28]
adding this to the header.php breaks the page 
Parse error: syntax error, unexpected ';' in /html/kirby/site/snippets/header.php on line 15

echo js(array(
  '//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js', // requires jQuery
  'assets/oembed/oembed.min.js'
);

everything else seems to work fine, i'm using kirby 2.1

**Comment by wirmachenbunt** [comment]
probably something else

**Comment by wirmachenbunt** [comment]
my full header.php

<!DOCTYPE html>
<html lang="en">
<head>

  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1.0">

  <title><?php echo $site->title()->html() ?> | <?php echo $page->title()->html() ?></title>
  <meta name="description" content="<?php echo $site->description()->html() ?>">
  <meta name="keywords" content="<?php echo $site->keywords()->html() ?>">

  <?php 
  echo css('assets/css/main.css');
  echo css('assets/oembed/oembed.css');
  echo js(array('//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js','assets/oembed/oembed.min.js');
  
  ?>

</head>
<body>

  <header class="header cf" role="banner">
    <a class="logo" href="<?php echo url() ?>">
      <img src="<?php echo url('assets/images/logo.svg') ?>" alt="<?php echo $site->title()->html() ?>" />
    </a>
    <?php snippet('menu') ?>
  </header>

**Comment by distantnative** [comment]
Oh sorry, there is missing one closing parenthese. It should be:

```php
echo js(array(
'//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js', // requires jQuery
'assets/oembed/oembed.min.js'
));
```

**Comment by wirmachenbunt** [comment]
works, sorry didnt see that :)

**Comment by distantnative** [comment]
:+1: not your mistake, I missed it in the documentation, but added it now

**Comment by distantnative** [comment]
If you have other questions, always feel free to ask. Also with suggestions/ideas.
And if the plugin helps you and you are able to share a few bucks to support the development, I'd really appreciate that: https://gumroad.com/l/kirby-oembed :smiley:

**Comment by wirmachenbunt** [comment]
hi nico,
i'm currently messing with kirby but the goal is to get my homepage done with it.
not sure if this is the best place to ask another question or open an issue.

when using the option lazyload, the play button sometimes just doesnt work (chrome latest version)

when i disable lazyload, the play icon will be displayed really oversized (same size as video) is there a way to keep its original size. the css is hard to mess with ;)

so either way, this doesnt work for me right now. see here : http://test.wirmachenbunt.de/

if the page goes out of testphase, i will support your development for sure :)

**Comment by distantnative** [comment]
@wirmachenbunt I'd need to test this myself to see, what's causing this. Unfortunately, I'll be quite busy till the end of the month and won't have the time to look at this right now :/ sorry

**Comment by wirmachenbunt** [comment]
no hurry..
btw. i was able to reproduce the play button not working on your site too. its just really inconsitent behaviour. seems like 99% it works and then it doesnt.
