### ISSUE TITLE
Problem with Collection.php's syntax

### ISSUE THREAD

**Issue by afincato** [distantnative/oembed#29]
I set up the plugin on my local dev environment and everything work as expected (no issues with other js plugin). When I uploaded everything on my web server I got this error:

> Parse error: syntax error, unexpected '$this' (T_VARIABLE) in /home/andrefin/www/kirby-v2/site/plugins/oembed/lib/Essence/Provider/Collection.php on line 117

If I took off the plugin, the page loads perfectly. 
Here you can see it — http://andrefincato.com/projects/ppp

Do you think it's some sort of non-compatibility with other js scripts I have loaded on the page?
I tried several time to upload a fresh unzipped version of your plugin to see if I left something behind, but no changes.

Any idea?

**Comment by distantnative** [comment]
No, there is no conflict with js.
But it looks like your server does not feature the required PHP version (5.5 or higher). It's a little problem, cause the plugin relies on some libraries at the moment that moved the requirements to PHP 5.5 - I'll try in feature releases to replace them with something less demanding.

**Comment by afincato** [comment]
OK! Thank you. At least I know it's just because of the old php version.
