### ISSUE TITLE
page works locally but breaks when uploaded

### ISSUE THREAD

**Issue by unworn** [distantnative/oembed#30]
I am using oembed for some vimeo videos. It seems to work fine locally but when I upload it to site, the page breaks. It doesn't show any content starting from where the first oembed is used. No errors in console.

**Comment by unworn** [comment]
update: I tried updating the php version on my hosting to 5.5 and that fixed things...for a while. Till it broke again. And I didn't change anything. help!

**Comment by distantnative** [comment]
Have you activated debug mode in Kirby's config.php?
