### ISSUE TITLE
Add support for oEmbed

### ISSUE THREAD

**Issue by cweiske** [distantnative/oembed#31]
Your code is full of special handling of youtube, vimeo and others - but it lacks oEmbed support.

Please add oEmbed support, then you don't have to have all the special case handling.

I would then be able to embed code from my pastebin in a website, e.g. http://p.cweiske.de/214

**Comment by francoisromain** [comment]
Would this work with issuu?

**Comment by cweiske** [comment]
Yes, because issuu supports oembed:

    <link rel="alternate" type="application/json+oembed" href="https://issuu.com/oembed?url=https%3A%2F%2Fissuu.com%2Fsamuelsantos52%2Fdocs%2Fnode.js_for_php_developers&amp;format=json" title="Node js for php developers">
    <link rel="alternate" type="text/xml+oembed" href="https://issuu.com/oembed?url=https%3A%2F%2Fissuu.com%2Fsamuelsantos52%2Fdocs%2Fnode.js_for_php_developers&amp;format=xml" title="Node js for php developers">

**Comment by francoisromain** [comment]
Cool! 
Which part of the code has to be changed to make this work?

**Comment by distantnative** [comment]
Will be possible with the upcoming 2.0.0 (already added to the develop branch but still work-in-progress).

**Comment by distantnative** [comment]
2.0.0 just got released. I know this comes super-late, but I would still love to hear from you if it works for your use cases.

**Comment by francoisromain** [comment]
oh cool. I will try and tell you thanks.
