### ISSUE TITLE
Conflict with wysiwyg plugin

### ISSUE THREAD

**Issue by benoitvb** [distantnative/oembed#32]
Hi,
I'm experiencing an issue that occurs when I insert an oembed tag in a wysiwyg field.
It works fine when I create the tag for the first time but when I try to save my page a second time the embed tag is turned into something like (oembed: [https://vimeo.com/videoID](https://vimeo.com/videoID)) and is rendered as a link tag.

Is there a workaround for this ?
Thanks for the plugin though :)

**Comment by distantnative** [comment]
What field are you referring to when you say "wysiwyg field"? Are you using a field plugin?

**Comment by benoitvb** [comment]
Yes, that one : https://github.com/storypioneers/kirby-wysiwyg

**Comment by distantnative** [comment]
@JonasDoebertin - is your plugin auto-converting URLs? And if so, is there a way to deactivate it?
