### ISSUE TITLE
Youtube link with specific time in the url

### ISSUE THREAD

**Issue by afincato** [distantnative/oembed#34]
Hello,
I am trying to embed a video from youtube, using the option for which you set at which point, within the video, you want to make it start (e.g. start the video at minute 1:50).

I am using youtube's `url` structure to do so, (e.g. `https://youtu.be/3c3jXPBG-NY?t=1h25s`), but when I post the link, the url is changed.

What can I do to resolve this?

Thanks!
André

**Comment by distantnative** [comment]
Sorry for being so late to the party. Sadly, YouTube does not use timecodes in their oembed api. So all the libraries also do not support it. I will see for the upcoming 2.0.0 if I can find a workaround.

**Comment by distantnative** [comment]
I found one - will be included in 2.0.0

**Comment by distantnative** [comment]
2.0.0 just got released. Would love to hear from you if it works for your use cases.

**Comment by afincato** [comment]
This is good news!

I updated the plugin replacing all the content inside `site/plugins/oembed` with the files of the version 2.0, but I got this error message when checking my site.

    Warning: require_once(/Users/andre/Sites/andrefincato/site/plugins/oembed/vendor/Embed/src/autoloader.php): failed to open stream: No such file or directory in /Users/andre/Sites/andrefincato/site/plugins/oembed/lib/autoload.php on line 49

**Comment by distantnative** [comment]
Ah sorry, I have been using the vendor library as a git submodule. But it seems to not be downloaded when downloading the plugin from GitHub. Will remove the submodule and add all files simply. Should be fixed with a 2.0.1 in a few minutes.

**Comment by distantnative** [comment]
Released 2.0.1 - hope this fixes your problems.

**Comment by afincato** [comment]
Thanks for being so quick.

Unfortunately, now I got a different error:

`Notice: Undefined variable: kirby in /Users/andre/Sites/andrefincato/site/plugins/oembed/oembed.php on line 18`

`Fatal error: Call to a member function set() on null in /Users/andre/Sites/andrefincato/site/plugins/oembed/oembed.php on line 18`

If you says it's easier to install the plugin through submodule, I'll try with that.

**Comment by distantnative** [comment]
Sorry for all the problems.
It hasn't been causing any problems for me, but I just pushed a potentially safer version of using `$kirby`. Could you try it again?

And no installing via submodules should now make no difference. It's a lack of the GitHub download that I missed, so I am now including all files directly.

**Comment by distantnative** [comment]
And if you try again, maybe try the version from the develop branch. More advanced with lots of fixes and improvements for 2.1.0 (to be released soon).

**Comment by afincato** [comment]
Thanks, I'll do.
I'm being trapped by a problem while updating `node.js` and other dependancies last night, so didn't reply you back. As soon as I'll figure this out and will be able to try the new plugin version, I'll update you about it!

**Comment by distantnative** [comment]
If there are more problems, hit me up on twitter (@distantnative) or via email (nico@getkirby.com). Maybe we can find a way with direct messages or so to solve the problems (since version 2 is a complete rewrite, there still might be some bugs in the details).
