### ISSUE TITLE
Youtube Playlist support

### ISSUE THREAD

**Issue by differenceclouds** [distantnative/oembed#35]
An option to get playlist info from the URL would be sweet! This adds the little playlist panel icon in the upper left of the video e.g. http://makenoisemusic.com/modules/dpo

**Comment by distantnative** [comment]
Will be possible with the upcoming 2.0.0 (already added to the develop branch but still work-in-progress).

**Comment by distantnative** [comment]
2.0.0 just got released. Would love to hear from you if it works for your use cases.

**Comment by differenceclouds** [comment]
Hi! Thanks for the update. I’m probably/definitely doing something wrong but I’m having a lot of trouble getting this new version up and running. For starters the installation instructions are slightly confusing. There’s an odd discrepancy here:

Download oEmbed <https://github.com/distantnative/oembed/zipball/master/> and add the files to site/plugins/oembed/
Add the necessary styles by including the following in the header:php <?= css('assets/plugins/oembed/css/oembed.css') ?>

So this is saying to create a new assets/plugins/oembed folder, and take the stuff out of the plugins/oembed/assets folder and put it in there? Or keep both? I’m probably missing something here. Also, I’m trying to use the oembed panel field type, and kirby doesn’t seem to be detecting it. Do I need to add something to the fields folder? Any tips on what I’m doing wrong?

**Comment by distantnative** [comment]
1. You do not need to add any asset folder. They are all included in the plugin folder in `site/plugins/oembed`. Kirby creates a route via `'assets/plugins/oembed/…` to these files, cause usually anything in the `site` folder is protected from access. So you really only have to add everything to `site/plugins/oembed` and then include `<?= css('assets/plugins/oembed/css/oembed.css') ?>` in your template - Kirby will link to the right asset file, it's already there (just be aware of this bug in the current beta: https://github.com/distantnative/oembed/issues/46)
2. If the panel can't find the oembed field, this is usually an indication that you are not using Kirby 2.3, which is required for oEmbed 2. Kirby 2.3 is currently in beta (https://getkirby.com/upcoming) and will be released soon.

**Comment by differenceclouds** [comment]
Cool, thank you for the quick reply. Got it up and running! It’s doing something strange and assigning an inline padding-top of  some generated number like 76.865% to the element wrapping the video and breaking my layout. I’ve overridden it with an !important padding-top declaration in my stylesheet, but I’m curious what’s this could be about?

**Comment by differenceclouds** [comment]
I apologize for my screwed up grammar also haha

**Comment by distantnative** [comment]
The padding-top is assigned for videos so that the oembed wrapper already fills the necessary space before the actual embedded media is loaded. In that way the layout doesn't jump around during loading. The "weird" number is generated from the aspect ratio of the embedded video.
If you have included the oembed CSS (see workaround for the current Kirby 2.3 bug: https://github.com/distantnative/oembed/issues/46) there should be no layout breaks. If so, I'd be interested in seeing them/getting a hold on your setup to test it.
