### ISSUE TITLE
Comma Value in Wrapper Style is breaking the output

### ISSUE THREAD

**Issue by SirNovi** [distantnative/oembed#57]
Hi there, thanks for the cool plugin!  I found a little Bug that can completely kill the output on the website. 

I'm putting together a website and after updating to the newest kirby version and the newest version of oembed my testvideo did not show up in the frontend anymore. 

After a bit of investigation I found a value of "padding-top: 42,5%" in the wrapper element. And Chrome correctly calls this 'Invalid Property Value'. The correct value would be 42.5% 

My quick fix to this was to run the return of `getAspectRatio()` through a `str_replace(',', '.',`

Maybe you'll find a better fix for it. 

Cheers 
Novi

**Comment by distantnative** [comment]
Can you provide an example link where it happens? The Embed library should actually always return a dot-separated value for `aspectRatio`.

**Comment by SirNovi** [comment]
I can't offer a link to the site at this moment. 

I used this video for testing purposes: 
https://vimeo.com/77122184

**Comment by distantnative** [comment]
Hmm, for me it works without any problems - could it be due to any of your server settings?

<img width="678" alt="screen shot 2016-06-10 at 18 04 41" src="https://cloud.githubusercontent.com/assets/3788865/15970639/ee7a3b46-2f35-11e6-8744-64cf95015679.png">

**Comment by SirNovi** [comment]
I have no clue. If you have an idea which setting could be causing this I could check. But I'm not enough of a programmer to even have a clue what could cause this.

**Comment by distantnative** [comment]
Just released 2.2.0 with a fix included.
