### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by strukturart** [distantnative/oembed#58]
Hello,

installed with kirby cli, what did I do wrong?
```
Warning: mkdir(): Permission denied in /....../site/plugins/oembed/lib/cache.php on line 12
```

getKirby 2.3.1

**Comment by distantnative** [comment]
The plugin tries to create the following folder: `site/cache/oembed` but is not allowed. If you create it manually, it should work as well.

**Comment by strukturart** [comment]
Thanks **distantnative** the permisson error are solved.
Now it works on my local test server but on the live server the have a new error message:
```
Kein Medium gefunden für https://youtu.be/jJDDSFuIj_w
```

**Comment by distantnative** [comment]
I tried to reproduce the error, but easily got the correct embed:
<img width="933" alt="screen shot 2016-09-03 at 14 48 50" src="https://cloud.githubusercontent.com/assets/3788865/18224897/8eb52fd4-71e5-11e6-8b3f-550224899dee.png">
