### ISSUE TITLE
Global function not found

### ISSUE THREAD

**Issue by SQbiz** [distantnative/oembed#59]
On Kirby 2.3.0, the global function isn't found. The field type works in the panel, and I can still make it work with Kirbytext:

`<?= kirbytext('(oembed: https://www.youtube.com/watch?v=m2ua3O_fdCY)') ?>`

but no go with 

`<?= oembed('https://www.youtube.com/watch?v=m2ua3O_fdCY') ?>`

Anything simple I might be missing?

**Comment by Dhamu143** [comment]
i am also facing the same problem.  please inform me if you find the solutions :)

**Comment by distantnative** [comment]
Just got fixed on the develop branch and will be part of the next update. Sorry that it took so long.
