### ISSUE TITLE
Lazyload Play Button

### ISSUE THREAD

**Issue by simonscheiber** [distantnative/oembed#64]
I don't get the lazyload button working for **Vimeo**. `c::set('plugin.oembed.video.lazyload.btn', 'assets/plugins/oembed/images/play.png');` is defined in config.php, the .(s)css file hooked up, and the image in the appropriate directory. Lazyload itself works… but the play button does not. Does anyone have the same issue?

**Comment by distantnative** [comment]
Looks like I forgot this in the documentation: The play button overlay is disabled for Vimeo since Vimeo always includes its own play button in the thumbnails. But I'm open to suggestions...

**Comment by simonscheiber** [comment]
Ahh, alright, then I don't have to continue looking. Thanks for getting back to me so swiftly! 
I can't see the standard Vimeo play button, though that might be because of another plugin. I'll look into that.
