### ISSUE TITLE
Lazyload does not load with Vimeo

### ISSUE THREAD

**Issue by carstenheisterkamp** [distantnative/oembed#65]
When using oembed without any options to display a vimeo vid , it creates a video preview with a link to start the video but the video does not load and start after clicking the link. The code I used.

```
<?php snippet('header') ?>
    <div class="fs-video-wrapper"><?php echo $page->featured_video()->oembed() ?></div>
<?php snippet('footer') ?>
```

and backend pabel to add the video link

```
featured_video:
    label: Featured video
    type: oembed
    preview: true
    info: true
    cheatsheet: true
    height: 250px
```

video link
https://vimeo.com/160916103

It shows up perfectly in the panel

**Comment by distantnative** [comment]
I know I am way too late to the party, but your example link works perfectly for me, I cannot reproduce your issue. It still exists for you?

**Comment by carstenheisterkamp** [comment]
I still have the problem but I am wondering if it might be related to the local installation and my MAMP Server.
