### ISSUE TITLE
Oembed not working locally

### ISSUE THREAD

**Issue by wout** [distantnative/oembed#66]
First of all, thanks for this great plugin!

I've set up a local environment (apache) for development of my site. When I try to use the oembed field locally I heft a "No medium found..." message for any of the possible sources (youtube, vimeo, twitter, ...). But after deploying the site to a live server, everything works as expected.

Now, this is not that much of an issue. It works where it should work, but It would be nice to test those things locally too. Now I have to deploy every time to see changes I made.

**Comment by distantnative** [comment]
I have too little information to recreate this issue. Since it is restricted to your local environment, I would guess it is rather caused by your setup, not the plugin.

**Comment by ErikBorra** [comment]
I had the same problem, due to php5-curl not being installed (a requirement of Embed).

**Comment by wout** [comment]
@ErikBorra That might be it indeed. Thanks for pointing that out.
